### ISSUE TITLE
Make a Landing page for the project.

### ISSUE THREAD

**Issue by Nafisa-Huda** [DevDevvy/responsive-video-windows#2]
The project doesn't contain any landing page/home page describing the project/website itself.

I'd like to make a straightforward landing page that will give more clarity to users about what "Randall's Windows" is all about.

**Comment by DevDevvy** [comment]
You are right! I focused so much on a ReadMe that I didn't put info in the actual app anywhere. You are welcome to make a landing page and submit a PR. Otherwise I will write one out later this week. Thank you for contributing and I'll talk to you later!

**Comment by Nafisa-Huda** [comment]
Awesome! Will be working on it today then.
